kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "verdaccio.fullname" . }}
  labels:
    app: {{ include "verdaccio.name" . }}
    chart: {{ include "verdaccio.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "verdaccio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "verdaccio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: verdaccio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4873
              protocol: TCP
          env:
            - name: VERDACCIO_PORT
              value: "4873"
            - name: VERDACCIO_CONFIG
              value: /verdaccio/conf/config.yaml
            - name: VERDACCIO_STORAGE
              value: /verdaccio/storage
#          volumeMounts:
#            - name: config-volume
#              mountPath: /verdaccio/conf
#            - name: storage-volume
#              mountPath: /verdaccio/storage
#      volumes:
#        - name: config-volume
#          configMap:
#            name: {{ include "verdaccio.fullname" . }}-config
#        - name: storage-volume
#          persistentVolumeClaim:
#            claimName: {{ include "verdaccio.fullname" . }}-pvc